# Generated by Django 3.0.3 on 2020-04-27 06:58

from django.db import migrations, models
import imagedb.images.infrastructure
import imagedb.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=imagedb.images.infrastructure.PrivateMediaStorage(), upload_to=imagedb.images.models.user_directory_path),
        ),
    ]
